### ISSUE TITLE
Social sharing images

### ISSUE THREAD

**Issue by yourheropaul** [endiangroup/endian.io#1]
These are in Google Drive. There are OG and twitter-appropriate images at least.

**Comment by adamking** [comment]
Added the following to head:

head
  meta charset="utf-8"
  meta http-equiv="X-UA-Compatible" content="IE=edge"
  meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"

  title {{ .Title }}
  meta name="description" content="{{ .Site.Params.description }}"
  meta name="author" content="{{ .Site.Params.name }}"

  meta property="og:url" content="{{ .Site.BaseURL }}"
  meta property="og:title" content="{{ .Title }}"
  meta property="og:description" content="{{ .Site.Params.description }}"
  meta property="og:image" content={{"endian-social-1200x630.png" | absURL}}

  meta name="twitter:title" content="{{ .Title }}"
  meta name="twitter:description" content="{{ .Site.Params.description }}"
  meta name="twitter:image" content={{"endian-social-1200x630.png" | absURL}}
  meta name="twitter:card" content="summary_large_image"

  link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"
  link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"
  link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"
  link rel="manifest" href="/manifest.json"
  link rel="mask-icon" href="/safari-pinned-tab.svg" color="#000000"
  meta name="theme-color" content="#000000"

  link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet"
  link href="/css/sherpa.css?v={{getenv "GITHASH"}}" rel="stylesheet"

**Comment by adamking** [comment]
Let me know if these are sufficient so we can close this.

**Comment by yourheropaul** [comment]
Looks good, let's close this
