### ISSUE TITLE
Social proof

### ISSUE THREAD

**Issue by adrianduke** [endiangroup/endian.io#17]
We now have 2 quotes from different companies that we'd like to display on the site. The first being:

"Endian hired our entire product team and as a testament to the quality of hires and their work we've since raised multi-million dollar funding rounds." -- Eiland Glover, CEO, Kowala Inc.

**Comment by adrianduke** [comment]
Second quote:

“It’s always a pleasure working with Endian. Their ability to understand our business is second to none. We think of them as an extension of ourselves.” -- Sam Labs

**Comment by aleksandramalchrzyk** [comment]
Could you remove my name from the quote I have not provided you with and that was used unlawfully and misleadingly on your website, please? Thanks.

**Comment by adrianduke** [comment]
@aleksandramalchrzyk -- I believe we had a conversation a few years ago on LinkedIn regarding this, you were working with Kai Posner and provided him the quote. We removed your name from the quote on the website (www.endian.io) at the time, I can edit the comment above as well to remove the attribution. No offence intended.

**Comment by aleksandramalchrzyk** [comment]
Your belief is a correct one. I did not provide the quote - its is made up and was used against my will.
Yes, that is what I am after - the editing of the comment above. Thanks!
