### ISSUE TITLE
Profile images have done a bit dwanky

### ISSUE THREAD

**Issue by yourheropaul** [endiangroup/endian.io#29]
I don't know if they were re-cut, but they look a little strange. My image has a thick circle on the left hand side, and they have lost some detail.

**Comment by adamking** [comment]
Can Cat redo these? It is an issue with the SVG from Illustrator.

**Comment by yourheropaul** [comment]
I've re-cut them in inkscape, the manliest of SVG editors. See them in the [drive directory](https://drive.google.com/open?id=1asVCkNPqmhmU-OOmQnMuV9KnQNST5zuL).

**Comment by adamking** [comment]
Updated and fixed.
