### ISSUE TITLE
Main title text

### ISSUE THREAD

**Issue by yourheropaul** [endiangroup/endian.io#5]
It looks a little bit sparse and lost. I the font size is too small. It looks more like the design at 2.5rem on my screen. Also the line height is in pixels, which may case scaling problems.

**Comment by adamking** [comment]
@yourheropaul To what text are you referring?

**Comment by yourheropaul** [comment]
The h1s: 'we're not an agency', etc.

![2018-08-13-085747_3840x2075_scrot](https://user-images.githubusercontent.com/50168/44019527-fac0d74e-9ed6-11e8-8dcf-5b156dec7fd4.png)

They look a little small, and a result they look off-centre.
