### ISSUE TITLE
The Endian Way garden path text is misaligned

### ISSUE THREAD

**Issue by yourheropaul** [endiangroup/endian.io#7]
There are also some giant spaces between the paragraphs:

![See screenshot](https://user-images.githubusercontent.com/50168/43990950-aa28c01c-9d5a-11e8-94db-b7d23b3384de.png)

**Comment by adamking** [comment]
This section will be the end of me.

**Comment by adamking** [comment]
It turns out I did a bad job fixing this. Reopening.

**Comment by yourheropaul** [comment]
This still looks like the screenshot above, at least for me.
